version: '3'

services:

  app:
    depends_on:
      - mysql
    build:
      context: ./docker/app
    ports:
      - "8000:8000"
    env_file:
      - ./docker/app/.env

  mysql:
      build:
        context: ./docker/mysql
      ports:
        - "3306:3306"
      env_file:
        - ./docker/mysql/.env