version: '3'

services:

  app:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./docker/app/.env

  db:
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - "3306:3306"
      - "3306"
    env_file:
      - ./docker/mysql/.env